--
-- Name: tb_rede_mt; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_rede_mt (
    id bigint NOT NULL,
    codigo character varying(255),
    nome character varying(255),
    tensao_nominal double precision,
    substacao_id bigint
);


--
-- Name: tb_rede_mt_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_rede_mt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_rede_mt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_subestacao; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tb_subestacao (
    id bigint NOT NULL,
    codigo character varying(255),
    latitude double precision,
    longitude double precision,
    nome character varying(255)
);


--
-- Name: tb_subestacao_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tb_subestacao ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tb_subestacao_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tb_rede_mt tb_rede_mt_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_rede_mt
    ADD CONSTRAINT tb_rede_mt_pkey PRIMARY KEY (id);


--
-- Name: tb_subestacao tb_subestacao_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_subestacao
    ADD CONSTRAINT tb_subestacao_pkey PRIMARY KEY (id);


--
-- Name: tb_rede_mt fkn3v3tx7r2wpiq10nks95l9r0r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tb_rede_mt
    ADD CONSTRAINT fkn3v3tx7r2wpiq10nks95l9r0r FOREIGN KEY (substacao_id) REFERENCES public.tb_subestacao(id);


--
-- PostgreSQL database dump complete
--

